wonjoejo/project

src/main/java/com/wonjoejo/myapp/domain/BaseCategoryDTO.java
src/main/java/com/wonjoejo/myapp/domain/BaseCategoryVO.java
src/main/java/com/wonjoejo/myapp/mapper/BaseCategoryMapper.java
src/main/java/com/wonjoejo/myapp/mapper/BoxMapper.java
src/main/resources/com/wonjoejo/myapp/mapper/BaseCategoryMapper.xml
src/main/resources/com/wonjoejo/myapp/mapper/BoxMapper.xml
src/test/java/com/wonjoejo/myapp/mapper/BaseCategoryTests.java
src/test/java/com/wonjoejo/myapp/mapper/BoxMapperTests.java

수정 BaseCategory mapper

---

src/main/java/com/wonjoejo/myapp/domain/BaseCategoryDTO.java
src/main/java/com/wonjoejo/myapp/mapper/BoxMapper.java
src/main/resources/com/wonjoejo/myapp/mapper/BaseCategoryMapper.xml
src/test/java/com/wonjoejo/myapp/mapper/BoxMapperTests.java

baseCategory Error

---

src/main/java/com/wonjoejo/myapp/controller/GroupController.java
src/main/java/com/wonjoejo/myapp/domain/BoxPermissionVO.java
src/main/java/com/wonjoejo/myapp/mapper/GroupMapper.java
src/main/java/com/wonjoejo/myapp/service/GroupService.java
src/main/java/com/wonjoejo/myapp/service/GroupServiceImpl.java
src/main/resources/com/wonjoejo/myapp/mapper/GroupMapper.xml
src/main/webapp/WEB-INF/views/box/list.jsp
src/main/webapp/resources/assets/css/box.css

box.css 수정

---

src/main/java/com/wonjoejo/myapp/controller/BoardController.java
src/main/java/com/wonjoejo/myapp/mapper/BoardMapper.java
src/main/java/com/wonjoejo/myapp/service/BoardService.java
src/main/java/com/wonjoejo/myapp/service/BoardServiceImpl.java
src/main/resources/com/wonjoejo/myapp/mapper/BoardMapper.xml
src/test/java/com/wonjoejo/myapp/controller/BoardControllerTests.java
src/test/java/com/wonjoejo/myapp/mapper/BoardMapperTests.java
src/test/java/com/wonjoejo/myapp/service/BoardServiceTests.java

mapper, service, controller 완료

umji mapper, service, controller

---

src/main/java/com/wonjoejo/myapp/controller/AdminController.java
src/main/java/com/wonjoejo/myapp/controller/MemberController.java
src/main/java/com/wonjoejo/myapp/domain/LoginDTO.java
src/main/java/com/wonjoejo/myapp/domain/MemberDTO.java
src/main/java/com/wonjoejo/myapp/domain/MemberVO.java
src/main/java/com/wonjoejo/myapp/mapper/AdminMapper.java
src/main/java/com/wonjoejo/myapp/mapper/MemberMapper.java
src/main/java/com/wonjoejo/myapp/service/AdminService.java
src/main/java/com/wonjoejo/myapp/service/AdminServiceImpl.java
src/main/java/com/wonjoejo/myapp/service/MemberService.java
src/main/java/com/wonjoejo/myapp/service/MemberServiceImpl.java
src/main/resources/com/wonjoejo/myapp/mapper/AdminMapper.xml
src/main/resources/com/wonjoejo/myapp/mapper/MemberMapper.xml
src/main/webapp/WEB-INF/views/member/list.jsp
src/test/java/com/wonjoejo/myapp/controller/AdminControllerTests.java
src/test/java/com/wonjoejo/myapp/controller/MemberControllerTests.java
src/test/java/com/wonjoejo/myapp/mapper/AdminMapperTests.java
src/test/java/com/wonjoejo/myapp/mapper/MemberMapperTests.java
src/test/java/com/wonjoejo/myapp/service/AdminServiceTests.java
src/test/java/com/wonjoejo/myapp/service/MemberServiceTests.java

회원가입, 수정, 삭제 & 관리자 test 완료

---

src/main/webapp/WEB-INF/views/box/createview.jsp
src/main/webapp/resources/assets/css/box.css

boxcreate.jsp css 수정

---

src/main/java/com/wonjoejo/myapp/controller/ProductController.java
src/test/java/com/wonjoejo/myapp/controller/ProductControllerTests.java

UPDATE Category insert test

---

src/main/java/com/wonjoejo/myapp/mapper/ProductMapper.java
src/main/resources/com/wonjoejo/myapp/mapper/ProductMapper.xml
src/test/java/com/wonjoejo/myapp/mapper/ProductMapperTests.java

ADD category detail test in Product

ADD category detail test in Product

---

myapp.iml
src/main/java/com/wonjoejo/myapp/controller/ProductController.java
src/main/java/com/wonjoejo/myapp/mapper/ProductMapper.java
src/main/java/com/wonjoejo/myapp/service/ProductService.java
src/main/java/com/wonjoejo/myapp/service/ProductServiceImpl.java
src/main/resources/com/wonjoejo/myapp/mapper/ProductMapper.xml
src/main/webapp/WEB-INF/views/category/detail.jsp
src/main/webapp/WEB-INF/views/product/detail.jsp
src/main/webapp/WEB-INF/views/product/edit.jsp
src/main/webapp/WEB-INF/views/product/insertview.jsp
src/main/webapp/WEB-INF/views/product/list.jsp
src/test/java/com/wonjoejo/myapp/controller/BaseCategoryControllerTests.java
src/test/java/com/wonjoejo/myapp/controller/ProductControllerTests.java
src/test/java/com/wonjoejo/myapp/mapper/BaseCategoryMapperTests.java
src/test/java/com/wonjoejo/myapp/mapper/ProductMapperTests.java
src/test/java/com/wonjoejo/myapp/service/ProductServiceTests.java

ADD category edit, detail test & view in product

ADD category edit, detail test & view in product

---

src/main/java/com/wonjoejo/myapp/controller/BoardController.java
src/main/java/com/wonjoejo/myapp/domain/BoardVO.java
src/main/java/com/wonjoejo/myapp/mapper/BoardMapper.java
src/main/java/com/wonjoejo/myapp/service/BoardService.java
src/main/java/com/wonjoejo/myapp/service/BoardServiceImpl.java
src/main/resources/com/wonjoejo/myapp/mapper/BoardMapper.xml
src/main/webapp/WEB-INF/views/board/detail.jsp
src/main/webapp/WEB-INF/views/board/edit.jsp
src/main/webapp/WEB-INF/views/board/list.jsp
src/main/webapp/WEB-INF/views/board/write.jsp
src/main/webapp/resources/assets/css/board.css
src/main/webapp/resources/assets/js/board.js

umji write,detail,edit,delete,notice

umji write,detail,edit,delete,notice

---

.classpath
src/main/java/com/wonjoejo/myapp/controller/BoardController.java
src/main/java/com/wonjoejo/myapp/mapper/BoardMapper.java
src/main/java/com/wonjoejo/myapp/service/BoardService.java
src/main/java/com/wonjoejo/myapp/service/BoardServiceImpl.java
src/main/resources/com/wonjoejo/myapp/mapper/BoardMapper.xml
src/main/webapp/WEB-INF/views/board/noticelist.jsp

umji notice 

---

src/main/java/com/wonjoejo/myapp/controller/ProductController.java
src/main/java/com/wonjoejo/myapp/domain/ProductVO.java
src/main/java/com/wonjoejo/myapp/mapper/ProductMapper.java
src/main/java/com/wonjoejo/myapp/service/ProductServiceImpl.java
src/main/resources/com/wonjoejo/myapp/mapper/ProductMapper.xml
src/test/java/com/wonjoejo/myapp/mapper/ProductMapperTests.java
src/test/java/com/wonjoejo/myapp/service/ProductServiceTests.java

product list edit 

---

src/main/webapp/WEB-INF/views/product/list.jsp
src/main/webapp/resources/assets/css/product.css
src/test/java/com/wonjoejo/myapp/controller/BoxControllerTests.java
src/test/java/com/wonjoejo/myapp/controller/ProductControllerTests.java

product list  뷰를... 만졌따... 잘 되면 좋겠다...

product list view

---

src/main/java/com/wonjoejo/myapp/controller/MemberController.java

MemberController 오류

---

src/main/webapp/WEB-INF/views/product/list.jsp
src/main/webapp/resources/assets/css/product.css

Product List

---

src/main/webapp/WEB-INF/views/box/createview.jsp
src/main/webapp/WEB-INF/views/box/get.jsp

box > createview , get.jsp

---

src/main/java/com/wonjoejo/myapp/controller/BoxController.java
src/main/java/com/wonjoejo/myapp/controller/CategoryController.java
src/main/java/com/wonjoejo/myapp/controller/ProductController.java
src/main/webapp/WEB-INF/views/common/boxleft.jsp
src/main/webapp/WEB-INF/views/product/edit.jsp
src/main/webapp/WEB-INF/views/product/insertview.jsp
src/main/webapp/WEB-INF/views/product/list.jsp
src/main/webapp/resources/assets/css/boxleft.css

controller에 get 맵핑한거 httpSession 이랑 box_no addAttribute 넣어줌

product Controller / box Controller / product insert

---

src/main/java/com/wonjoejo/myapp/controller/BoxController.java
src/main/java/com/wonjoejo/myapp/controller/CategoryController.java
src/main/java/com/wonjoejo/myapp/controller/ProductController.java
src/main/webapp/WEB-INF/views/box/editview.jsp
src/main/webapp/WEB-INF/views/box/get.jsp
src/main/webapp/WEB-INF/views/category/detail.jsp
src/main/webapp/WEB-INF/views/category/edit.jsp
src/main/webapp/WEB-INF/views/common/boxleft.jsp
src/main/webapp/WEB-INF/views/product/detail.jsp
src/main/webapp/WEB-INF/views/product/edit.jsp
src/main/webapp/WEB-INF/views/product/insertview.jsp
src/main/webapp/WEB-INF/views/product/list.jsp
src/main/webapp/resources/assets/js/box.js

boxleft.jsp box_no 가져가게 수정 및 박스 수정 완성

boxleft.jsp box_no 가져가게 수정 및 박스 수정 완성

---

src/main/webapp/WEB-INF/views/product/insertview.jsp

product insertview.jsp

---

src/main/java/com/wonjoejo/myapp/controller/ProductController.java
src/main/webapp/WEB-INF/views/category/detail.jsp
src/main/webapp/WEB-INF/views/product/detail.jsp

ADD kakao 공유하기 in product detail

ADD kakao 공유하기 in product detail

---

src/main/java/com/wonjoejo/myapp/controller/ProductController.java
src/main/webapp/WEB-INF/views/product/detail.jsp
src/main/webapp/WEB-INF/views/product/insertview.jsp
src/main/webapp/WEB-INF/views/product/list.jsp
src/main/webapp/resources/assets/css/product.css
src/main/webapp/resources/assets/css/productDetail.css
src/test/java/com/wonjoejo/myapp/controller/ProductControllerTests.java

Product 사진 업로드

---

src/main/java/com/wonjoejo/myapp/controller/BoardController.java
src/main/webapp/WEB-INF/views/board/detail.jsp
src/main/webapp/WEB-INF/views/board/list.jsp
src/main/webapp/WEB-INF/views/board/noticelist.jsp
src/main/webapp/WEB-INF/views/board/noticewrite.jsp
src/main/webapp/WEB-INF/views/board/replywrite.jsp
src/main/webapp/WEB-INF/views/board/write.jsp
src/main/webapp/resources/assets/js/board.js

Session member_id 

---

src/main/java/com/wonjoejo/myapp/controller/BoardController.java
src/main/java/com/wonjoejo/myapp/controller/ProductController.java
src/main/resources/com/wonjoejo/myapp/mapper/ProductMapper.xml

excel data 들어감 성공

---

src/main/java/com/wonjoejo/myapp/controller/BoardController.java

umji controller edit

---

src/main/java/com/wonjoejo/myapp/controller/BoxController.java
src/main/java/com/wonjoejo/myapp/controller/ProductController.java
src/main/webapp/WEB-INF/views/box/list.jsp

excel 마무리 작업중

---

src/main/java/com/wonjoejo/myapp/controller/BoxController.java

alert test

---

src/main/java/com/wonjoejo/myapp/controller/BoxController.java
src/main/webapp/WEB-INF/views/box/createview.jsp
src/main/webapp/WEB-INF/views/box/get.jsp
src/main/webapp/WEB-INF/views/box/list.jsp
src/main/webapp/resources/assets/js/box.js

default img url 수정 (box list.jsp, box controller, box.js 참고해서 product 수정해주면 됨)

default img url 수정

---

src/main/java/com/wonjoejo/myapp/controller/CategoryController.java
src/main/java/com/wonjoejo/myapp/service/BaseCategoryServiceImpl.java
src/main/webapp/WEB-INF/views/index.jsp

BaseCategory delete

---

src/main/java/com/wonjoejo/myapp/controller/ProductController.java
src/main/webapp/WEB-INF/views/product/detail.jsp
src/main/webapp/WEB-INF/views/product/edit.jsp
src/main/webapp/WEB-INF/views/product/insertview.jsp
src/main/webapp/WEB-INF/views/product/list.jsp
src/main/webapp/resources/assets/css/productDetail.css

물품 상세보기에서 수정 / 등록된 이미지 표시 / 리스트로 이동 기능 구현

Product List & Detail & Edit

---

src/main/java/com/wonjoejo/myapp/controller/BoardController.java
src/main/java/com/wonjoejo/myapp/mapper/BoardMapper.java
src/main/java/com/wonjoejo/myapp/service/BoardService.java
src/main/java/com/wonjoejo/myapp/service/BoardServiceImpl.java
src/main/resources/com/wonjoejo/myapp/mapper/BoardMapper.xml
src/main/webapp/WEB-INF/views/board/detail.jsp
src/main/webapp/WEB-INF/views/board/edit.jsp
src/main/webapp/WEB-INF/views/board/list.jsp
src/main/webapp/WEB-INF/views/board/noticewrite.jsp
src/main/webapp/WEB-INF/views/board/replydetail.jsp
src/main/webapp/WEB-INF/views/board/replywrite.jsp
src/main/webapp/WEB-INF/views/board/write.jsp
src/main/webapp/resources/assets/css/board.css
src/main/webapp/resources/assets/js/board.js

add alldelete , sweetalert

---

src/main/java/com/wonjoejo/myapp/controller/GroupController.java
src/main/java/com/wonjoejo/myapp/mapper/GroupMapper.java
src/main/java/com/wonjoejo/myapp/service/GroupService.java
src/main/java/com/wonjoejo/myapp/service/GroupServiceImpl.java
src/main/java/com/wonjoejo/myapp/service/MemberService.java
src/main/resources/com/wonjoejo/myapp/mapper/GroupMapper.xml
src/main/resources/com/wonjoejo/myapp/mapper/ProductMapper.xml
src/main/webapp/WEB-INF/views/group/editview.jsp
src/main/webapp/resources/assets/css/group.css
src/main/webapp/resources/assets/js/group.js

group 권한 수정 및 양도 기능 완성

---

src/main/resources/com/wonjoejo/myapp/mapper/ProductMapper.xml
src/main/webapp/WEB-INF/views/box/get.jsp
src/main/webapp/WEB-INF/views/category/detail.jsp
src/main/webapp/resources/assets/css/baseCategory.css
src/main/webapp/resources/assets/css/box.css
src/main/webapp/resources/assets/js/baseCategory.js

box.get.jsp view단

---

src/main/java/com/wonjoejo/myapp/controller/BoardController.java
src/main/java/com/wonjoejo/myapp/mapper/BoardMapper.java
src/main/java/com/wonjoejo/myapp/service/BoardService.java
src/main/java/com/wonjoejo/myapp/service/BoardServiceImpl.java
src/main/resources/com/wonjoejo/myapp/mapper/BoardMapper.xml
src/main/webapp/WEB-INF/views/board/alert.jsp
src/main/webapp/WEB-INF/views/board/list.jsp
src/main/webapp/WEB-INF/views/board/noticedetail.jsp
src/main/webapp/WEB-INF/views/board/replydetail.jsp
src/main/webapp/resources/assets/css/board.css

qna_board 작동 마무리 

---

src/main/java/com/wonjoejo/myapp/controller/ProductController.java
src/main/java/com/wonjoejo/myapp/service/ProductServiceImpl.java
src/main/resources/com/wonjoejo/myapp/mapper/ProductMapper.xml
src/main/webapp/WEB-INF/views/product/detail.jsp
src/main/webapp/WEB-INF/views/product/edit.jsp
src/test/java/com/wonjoejo/myapp/controller/ProductControllerTests.java
src/test/java/com/wonjoejo/myapp/mapper/ProductMapperTests.java

Product 수정 / 삭제

---

src/main/webapp/WEB-INF/views/index.jsp
src/main/webapp/resources/assets/css/index.css
src/main/webapp/resources/assets/js/index.js

index tabbar

---

src/main/java/com/wonjoejo/myapp/controller/BoxController.java
src/main/webapp/WEB-INF/views/box/list.jsp
src/main/webapp/WEB-INF/views/group/editview.jsp
src/main/webapp/WEB-INF/views/product/list.jsp
src/main/webapp/resources/assets/js/productList.js

productList pagination

---

src/main/webapp/WEB-INF/views/product/list.jsp
src/main/webapp/resources/assets/js/productList.js

비동기 pagination 완성

---

src/main/webapp/WEB-INF/views/product/detail.jsp
src/main/webapp/resources/assets/js/product.js

product.js 변수처리 

---

src/main/java/com/wonjoejo/myapp/controller/GroupController.java
src/main/java/com/wonjoejo/myapp/controller/MemberController.java
src/main/resources/com/wonjoejo/myapp/mapper/GroupMapper.xml
src/main/webapp/WEB-INF/views/group/editview.jsp
src/main/webapp/WEB-INF/views/product/detail.jsp
src/main/webapp/WEB-INF/views/product/insertview.jsp
src/main/webapp/resources/assets/css/productDetail.css
src/main/webapp/resources/assets/js/group.js
src/main/webapp/resources/assets/js/mention.js
src/test/java/com/wonjoejo/myapp/service/GroupServiceTests.java

mention 기능 memo 부분에 추가

---

src/main/java/com/wonjoejo/myapp/controller/MemberController.java
src/main/java/com/wonjoejo/myapp/mapper/MemberMapper.java
src/main/java/com/wonjoejo/myapp/service/MemberService.java
src/main/java/com/wonjoejo/myapp/service/MemberServiceImpl.java
src/main/resources/com/wonjoejo/myapp/mapper/MemberMapper.xml
src/main/webapp/WEB-INF/views/member/login.jsp
src/main/webapp/WEB-INF/views/product/detail.jsp
src/main/webapp/resources/assets/css/login.css
src/main/webapp/resources/assets/js/login.js
src/test/java/com/wonjoejo/myapp/mapper/MemberMapperTests.java
src/test/java/com/wonjoejo/myapp/service/GroupServiceTests.java
src/test/java/com/wonjoejo/myapp/service/MemberServiceTests.java

ADD 아이디 찾기

---

src/main/java/com/wonjoejo/myapp/controller/GroupController.java
src/main/resources/com/wonjoejo/myapp/mapper/GroupMapper.xml
src/main/webapp/WEB-INF/views/group/editview.jsp
src/main/webapp/WEB-INF/views/group/grouplist.jsp
src/main/webapp/WEB-INF/views/group/permissionlist.jsp
src/main/webapp/resources/assets/js/group.js
src/test/java/com/wonjoejo/myapp/service/GroupServiceTests.java

group 추방까지 완료!

---

src/main/webapp/resources/assets/js/login.js

Edit member.js (pw 변경) 

---

src/main/java/com/wonjoejo/myapp/controller/ChartController.java
src/main/java/com/wonjoejo/myapp/controller/ProductController.java
src/main/webapp/WEB-INF/views/chart/get.jsp
src/main/webapp/WEB-INF/views/common/boxleft.jsp
src/main/webapp/WEB-INF/views/product/list.jsp
src/main/webapp/resources/assets/css/chart.css

ADD chart file

---

src/main/webapp/WEB-INF/views/product/detail.jsp
src/main/webapp/WEB-INF/views/product/edit.jsp
src/main/webapp/WEB-INF/views/product/insertview.jsp

Product 주석정리

---

src/main/java/com/wonjoejo/myapp/controller/ProductController.java
src/main/java/com/wonjoejo/myapp/domain/MemberTypeVO.java
src/main/java/com/wonjoejo/myapp/mapper/ProductMapper.java
src/main/java/com/wonjoejo/myapp/service/ProductService.java
src/main/java/com/wonjoejo/myapp/service/ProductServiceImpl.java
src/main/resources/com/wonjoejo/myapp/mapper/ProductMapper.xml
src/main/webapp/WEB-INF/views/product/detail.jsp
src/test/java/com/wonjoejo/myapp/mapper/ProductMapperTests.java

Product Member Type

---

src/main/java/com/wonjoejo/myapp/controller/MemberController.java
src/main/java/com/wonjoejo/myapp/interceptor/LoginInterceptor.java
src/main/java/com/wonjoejo/myapp/service/MemberServiceImpl.java
src/main/webapp/WEB-INF/views/common/myleft.jsp
src/main/webapp/WEB-INF/views/member/idCheck.jsp
src/main/webapp/WEB-INF/views/member/login.jsp
src/main/webapp/WEB-INF/views/member/myPage.jsp
src/main/webapp/WEB-INF/views/member/register.jsp
src/main/webapp/resources/assets/css/accountModal.css
src/main/webapp/resources/assets/css/login.css
src/main/webapp/resources/assets/css/myPage.css
src/main/webapp/resources/assets/css/register.css
src/main/webapp/resources/assets/js/login.js
src/main/webapp/resources/assets/js/myPage.js

member 탈퇴 등

---

src/main/java/com/wonjoejo/myapp/interceptor/LoginInterceptor.java
src/main/resources/com/wonjoejo/myapp/mapper/MemberMapper.xml
src/main/webapp/WEB-INF/views/admin/list.jsp
src/main/webapp/WEB-INF/views/admin/searchList0.jsp
src/main/webapp/WEB-INF/views/admin/searchList1.jsp
src/main/webapp/WEB-INF/views/member/login.jsp
src/main/webapp/WEB-INF/views/member/register.jsp
src/main/webapp/resources/assets/css/accountModal.css
src/main/webapp/resources/assets/css/admin.css
src/main/webapp/resources/assets/css/register.css
src/main/webapp/resources/assets/js/admin.js
src/main/webapp/resources/assets/js/register.js

add 유효성 검사, admin page 유형

---

src/main/java/com/wonjoejo/myapp/controller/MemberController.java
src/main/java/com/wonjoejo/myapp/interceptor/LoginInterceptor.java
src/main/webapp/WEB-INF/views/member/alert.jsp
src/main/webapp/WEB-INF/views/member/login.jsp
src/main/webapp/resources/assets/css/login.css

login 실패 alert

---

src/main/java/com/wonjoejo/myapp/domain/MemberTypeVO.java
src/main/resources/com/wonjoejo/myapp/mapper/ProductMapper.xml
src/main/webapp/WEB-INF/views/board/list.jsp
src/main/webapp/WEB-INF/views/index.jsp
src/main/webapp/WEB-INF/views/member/login.jsp
src/main/webapp/WEB-INF/views/member/loginIndex.jsp
src/main/webapp/WEB-INF/views/member/register.jsp
src/main/webapp/WEB-INF/views/product/list.jsp
src/main/webapp/resources/assets/css/index.css
src/main/webapp/resources/assets/js/productList.js

memeberTypeVO, css 여기저기

---

src/main/webapp/WEB-INF/views/box/detail.jsp
src/main/webapp/WEB-INF/views/chart/get.jsp
src/main/webapp/WEB-INF/views/group/grouplist.jsp
src/main/webapp/WEB-INF/views/product/list.jsp
src/main/webapp/resources/assets/css/product.css
src/main/webapp/resources/assets/js/box.js
src/main/webapp/resources/assets/js/productList.js

css 약간 정리, product list img download 기능 추가

css 약간 정리, product list img download 기능 추가

---

src/main/webapp/WEB-INF/views/board/list.jsp
src/main/webapp/WEB-INF/views/box/createview.jsp
src/main/webapp/WEB-INF/views/box/list.jsp
src/main/webapp/WEB-INF/views/common/boxleft.jsp
src/main/webapp/resources/assets/css/box.css
src/main/webapp/resources/assets/js/board.js

boxleft 아이콘수정 , boxlist, boxcreate 반응형수정

boxleft, boxlist, boxcreate, boardjs

---

src/main/webapp/WEB-INF/views/chart/get.jsp
src/main/webapp/WEB-INF/views/common/boxleft.jsp

1. boxmenu - box_no permission 객체에서 받아오는거 추가
2. chart-get box 이미지 src 최신버전으로 수정
3. chart-get dateList 이미지 src 오타 수정 (productList > dateList)

boxmenu, chart-get 수정

---

src/main/java/com/wonjoejo/myapp/controller/BoardController.java
src/main/webapp/WEB-INF/views/board/list.jsp
src/main/webapp/WEB-INF/views/product/edit.jsp
src/main/webapp/WEB-INF/views/product/insertview.jsp
src/main/webapp/resources/assets/js/productDetail.js
src/main/webapp/resources/assets/js/productEdit.js

product list img url 수정

---

src/main/webapp/WEB-INF/views/box/detail.jsp
src/main/webapp/WEB-INF/views/box/editview.jsp
src/main/webapp/WEB-INF/views/box/list.jsp
src/main/webapp/WEB-INF/views/category/detail.jsp
src/main/webapp/WEB-INF/views/common/boxleft.jsp
src/main/webapp/WEB-INF/views/common/boxleftmobile.jsp
src/main/webapp/WEB-INF/views/common/left.jsp
src/main/webapp/WEB-INF/views/product/list.jsp
src/main/webapp/resources/assets/css/box.css
src/main/webapp/resources/assets/css/boxleft.css
src/main/webapp/resources/assets/css/boxleftmobile.css
src/main/webapp/resources/assets/css/left.css
src/main/webapp/resources/assets/css/product.css
src/main/webapp/resources/assets/js/boxleftmobile.js

boxleftmobile 추가생성 
나의박스, 물품리스트, 카테고리에  boxleftmobile추가
css 일부 수정

boxleftmobile, 나의박스, 물품리스트, 카테고리에 추가

---

src/main/java/com/wonjoejo/myapp/controller/ChartController.java
src/main/webapp/WEB-INF/views/admin/list.jsp
src/main/webapp/WEB-INF/views/product/detail.jsp
src/main/webapp/resources/assets/css/admin.css
src/main/webapp/resources/assets/css/productDetail.css
src/main/webapp/resources/assets/js/productDetail.js

차트 오류, 댓글 수정 

---

src/main/webapp/WEB-INF/views/product/detail.jsp
src/main/webapp/resources/assets/css/productDetail.css

멘션 아이디 리스트 위치 수정 

---

src/main/java/com/wonjoejo/myapp/controller/KakaoController.java
src/main/webapp/WEB-INF/views/member/myPage.jsp

kakao logout

---

src/main/webapp/WEB-INF/views/box/createview.jsp
src/main/webapp/WEB-INF/views/product/detail.jsp
src/main/webapp/resources/assets/js/productDetail.js

box create 기업/개인 구분 추가

---

src/main/java/com/wonjoejo/myapp/controller/KakaoController.java
src/main/java/com/wonjoejo/myapp/interceptor/LoginInterceptor.java

add authkey

---

src/main/java/com/wonjoejo/myapp/controller/GroupController.java
src/main/java/com/wonjoejo/myapp/controller/ProductController.java
src/main/resources/com/wonjoejo/myapp/mapper/GroupMapper.xml
src/main/resources/com/wonjoejo/myapp/mapper/ProductMapper.xml
src/main/webapp/WEB-INF/views/group/grouplist.jsp
src/main/webapp/resources/assets/css/group.css
src/main/webapp/resources/assets/js/grouplist.js

product controller, mapper edit 기능 추가

---

src/main/java/com/wonjoejo/myapp/controller/ProductController.java
src/main/resources/com/wonjoejo/myapp/mapper/ProductMapper.xml
src/main/webapp/WEB-INF/views/product/detail.jsp
src/main/webapp/WEB-INF/views/product/edit.jsp

ADD update 

---

src/main/webapp/WEB-INF/views/product/detail.jsp
src/main/webapp/WEB-INF/views/product/edit.jsp
src/test/java/com/wonjoejo/myapp/mapper/ProductMapperTests.java
src/test/java/com/wonjoejo/myapp/service/ProductServiceTests.java

update_ date 오류 수정

---

src/main/webapp/WEB-INF/views/common/boxleft.jsp
src/main/webapp/WEB-INF/views/common/boxleftmobile.jsp
src/main/webapp/WEB-INF/views/common/leftmobile.jsp
src/main/webapp/resources/assets/css/boxleft.css
src/main/webapp/resources/assets/css/boxleftmobile.css

box-left 수정 

---

src/main/java/com/wonjoejo/myapp/controller/ProductController.java
src/main/java/com/wonjoejo/myapp/mapper/ProductMapper.java
src/main/resources/com/wonjoejo/myapp/mapper/ProductMapper.xml
src/test/java/com/wonjoejo/myapp/mapper/ProductMapperTests.java
src/test/java/com/wonjoejo/myapp/service/ProductServiceTests.java

QR생성 - 멤버Type 확인

---

src/main/webapp/WEB-INF/views/index.jsp
src/main/webapp/resources/assets/css/index.css

index 슬라이드 글씨 수정 

---

src/main/java/com/wonjoejo/myapp/controller/BoxController.java
src/main/webapp/WEB-INF/views/box/list.jsp
src/main/webapp/WEB-INF/views/common/left.jsp
src/main/webapp/WEB-INF/views/product/detail.jsp
src/main/webapp/WEB-INF/views/product/insertview.jsp
src/main/webapp/WEB-INF/views/product/list.jsp
src/main/webapp/resources/assets/js/box.js
src/main/webapp/resources/assets/js/boxalert.js
src/main/webapp/resources/assets/js/boxmenu.js
src/main/webapp/resources/assets/js/productList.js

1. product list img 출력 부분 (default img local로 소스 변경)
2. 박스 생성시 alert 추가
3. 박스 초대 기능 sweetalert으로 변경

product list img 외

---

src/main/webapp/WEB-INF/views/board/noticelist.jsp
src/main/webapp/resources/assets/css/board.css

공지페이지 돌아가기버튼, 페이지

---

src/main/webapp/WEB-INF/views/common/boxleft.jsp
src/main/webapp/resources/assets/js/inboxmenu.js

box 내부 메뉴 활성화 기능 추가

---

src/main/java/com/wonjoejo/myapp/controller/GroupController.java
src/main/webapp/WEB-INF/views/group/grouplist.jsp
src/main/webapp/resources/assets/css/group.css
src/main/webapp/resources/assets/js/grouplist.js

group 권한 수정 오류 수정 / group modal css 수정중

group 권한 수정 오류 수정 / group modal css 수정중

---

src/main/webapp/WEB-INF/views/chart/get.jsp
src/main/webapp/WEB-INF/views/product/detail.jsp
src/main/webapp/WEB-INF/views/product/edit.jsp
src/main/webapp/WEB-INF/views/product/insertview.jsp
src/main/webapp/resources/assets/css/chart.css
src/main/webapp/resources/assets/js/productDetail.js

insert 유효성, 차트 수정

---

src/main/webapp/WEB-INF/views/box/detail.jsp
src/main/webapp/WEB-INF/views/group/grouplist.jsp
src/main/webapp/resources/assets/css/box.css
src/main/webapp/resources/assets/css/product.css
src/main/webapp/resources/assets/js/box.js
src/main/webapp/resources/assets/js/inboxmenu.js

box delete 오류 수정

---

src/main/webapp/WEB-INF/views/member/register.jsp
src/main/webapp/resources/assets/css/register.css
src/main/webapp/resources/assets/js/register.js

register 유효성 검사 alert

---

src/main/webapp/WEB-INF/views/common/myleft.jsp
src/main/webapp/WEB-INF/views/group/grouplist.jsp
src/main/webapp/resources/assets/css/group.css
src/main/webapp/resources/assets/css/myPage.css
src/main/webapp/resources/assets/js/grouplist.js
src/main/webapp/resources/assets/js/myleft.js

mypage 메뉴 활성화 처리 및 초대코드 css 완성

mypage 메뉴 활성화 처리 및 초대코드 css 완성

---

src/main/webapp/WEB-INF/views/group/grouplist.jsp
src/main/webapp/resources/assets/js/grouplist.js

group 초대 css 완성

---

src/main/webapp/WEB-INF/views/board/noticelist.jsp
src/main/webapp/WEB-INF/views/box/createview.jsp
src/main/webapp/WEB-INF/views/chart/get.jsp
src/main/webapp/WEB-INF/views/group/editview.jsp
src/main/webapp/WEB-INF/views/group/grouplist.jsp
src/main/webapp/WEB-INF/views/group/permissionlist.jsp
src/main/webapp/WEB-INF/views/product/detail.jsp
src/main/webapp/WEB-INF/views/product/edit.jsp
src/main/webapp/WEB-INF/views/product/insertview.jsp
src/main/webapp/resources/assets/css/board.css
src/main/webapp/resources/assets/css/box.css

그룹 , 차트, 물건등록 에 모바일 메뉴 추가
q&a css 수정 
스크롤 수정

모바일 메뉴 추가, q&a css 수정, 스크롤 수정 

---

src/main/webapp/WEB-INF/views/product/detail.jsp
src/main/webapp/WEB-INF/views/product/list.jsp
src/main/webapp/resources/assets/js/product.js

QR 다운로드 아이콘

---

src/main/webapp/WEB-INF/views/board/list.jsp
src/main/webapp/WEB-INF/views/common/boxleftmobile.jsp
src/main/webapp/WEB-INF/views/index.jsp
src/main/webapp/resources/assets/css/board.css

board 반응형 수정

---

src/main/webapp/WEB-INF/views/member/login.jsp
src/main/webapp/WEB-INF/views/member/register.jsp
src/main/webapp/resources/assets/css/login.css
src/main/webapp/resources/assets/css/register.css
src/main/webapp/resources/assets/js/register.js

login, register 수정

---

src/main/webapp/WEB-INF/views/common/left.jsp
src/main/webapp/WEB-INF/views/product/detail.jsp
src/main/webapp/WEB-INF/views/product/edit.jsp
src/main/webapp/resources/assets/css/left.css
src/main/webapp/resources/assets/js/boxmenu.js
src/main/webapp/resources/assets/js/mention.js
src/main/webapp/resources/assets/js/productDetail.js

mention 수정중

---

src/main/webapp/resources/assets/js/mention.js

mention 기능 고침

---

src/main/webapp/WEB-INF/views/common/boxleftmobile.jsp
src/main/webapp/WEB-INF/views/index.jsp
src/main/webapp/WEB-INF/views/member/login.jsp
src/main/webapp/WEB-INF/views/member/loginIndex.jsp
src/main/webapp/WEB-INF/views/member/register.jsp
src/main/webapp/resources/assets/css/board.css
src/main/webapp/resources/assets/css/login.css

로그인 모바일 반응형 

---

src/main/webapp/WEB-INF/views/board/list.jsp
src/main/webapp/resources/assets/css/board.css

Q&A 게시판 아이디 마스킹 / admin 닉네임 변환  / 보드 리스트 주석 정리

Q&A 게시판 아이디 마스킹

---

src/main/java/com/wonjoejo/myapp/controller/ProductController.java
src/main/webapp/WEB-INF/views/board/detail.jsp
src/main/webapp/WEB-INF/views/board/list.jsp
src/main/webapp/WEB-INF/views/board/replydetail.jsp
src/main/webapp/WEB-INF/views/board/searchlist.jsp
src/main/webapp/WEB-INF/views/box/list.jsp
src/main/webapp/WEB-INF/views/common/left.jsp
src/main/webapp/WEB-INF/views/product/detail.jsp
src/main/webapp/WEB-INF/views/product/list.jsp
src/main/webapp/resources/assets/css/box.css
src/main/webapp/resources/assets/css/product.css
src/main/webapp/resources/assets/css/productDetail.css
src/main/webapp/resources/assets/js/boxmenu.js
src/main/webapp/resources/assets/js/productList.js

자잘한거 수정, crossorigin 다시 수정

---

src/main/webapp/resources/assets/js/productList.js

검색결과 crossorigin 적용

---

src/main/java/com/wonjoejo/myapp/controller/BoxController.java
src/main/java/com/wonjoejo/myapp/controller/MemberController.java
src/main/java/com/wonjoejo/myapp/domain/BoxPermissionBoxDTO.java
src/main/java/com/wonjoejo/myapp/domain/BoxPermissionBoxVO.java
src/main/java/com/wonjoejo/myapp/mapper/BoxMapper.java
src/main/java/com/wonjoejo/myapp/mapper/GroupMapper.java
src/main/java/com/wonjoejo/myapp/mapper/MemberMapper.java
src/main/java/com/wonjoejo/myapp/service/GroupService.java
src/main/java/com/wonjoejo/myapp/service/GroupServiceImpl.java
src/main/java/com/wonjoejo/myapp/service/MemberService.java
src/main/java/com/wonjoejo/myapp/service/MemberServiceImpl.java
src/main/resources/com/wonjoejo/myapp/mapper/GroupMapper.xml
src/main/resources/com/wonjoejo/myapp/mapper/MemberMapper.xml
src/main/webapp/WEB-INF/views/box/detail.jsp
src/main/webapp/WEB-INF/views/member/myPage.jsp
src/main/webapp/WEB-INF/views/member/register.jsp
src/main/webapp/resources/assets/css/myPage.css
src/main/webapp/resources/assets/js/box.js
src/main/webapp/resources/assets/js/myPage.js
src/main/webapp/resources/assets/js/register.js
src/test/java/com/wonjoejo/myapp/service/GroupServiceTests.java
src/test/java/com/wonjoejo/myapp/service/MemberServiceTests.java

회원수정 유효성 검사,  회원 탈퇴

---

src/main/webapp/WEB-INF/views/board/list.jsp

Q&A게시판 아이디 마스킹 - 작성자 본인 아이디일 경우에는 아이디 전체 보여주기

Q&A게시판 아이디 마스킹

---

src/main/java/com/wonjoejo/myapp/controller/CategoryController.java
src/main/java/com/wonjoejo/myapp/domain/DeleteCategoryDTO.java
src/main/java/com/wonjoejo/myapp/domain/DeleteCategoryVO.java
src/main/java/com/wonjoejo/myapp/mapper/BaseCategoryMapper.java
src/main/java/com/wonjoejo/myapp/service/BaseCategoryService.java
src/main/java/com/wonjoejo/myapp/service/BaseCategoryServiceImpl.java
src/main/resources/com/wonjoejo/myapp/mapper/BaseCategoryMapper.xml
src/main/webapp/WEB-INF/views/category/detail.jsp
src/main/webapp/WEB-INF/views/product/edit.jsp
src/main/webapp/WEB-INF/views/product/insertview.jsp
src/main/webapp/resources/assets/css/productDetail.css
src/main/webapp/resources/assets/js/baseCategory.js
src/test/java/com/wonjoejo/myapp/mapper/BaseCategoryMapperTests.java
src/test/java/com/wonjoejo/myapp/service/BaseCategoryServiceTests.java

category 오류 수정

---

src/main/java/com/wonjoejo/myapp/controller/BoxController.java
src/main/java/com/wonjoejo/myapp/controller/HomeController.java
src/main/java/com/wonjoejo/myapp/controller/ProductController.java
src/main/webapp/WEB-INF/views/member/register.jsp
src/main/webapp/WEB-INF/views/product/detail.jsp
src/main/webapp/resources/assets/css/productDetail.css
src/main/webapp/resources/assets/js/register.js

회원가입 오류 수정

---

src/main/webapp/WEB-INF/views/board/detail.jsp
src/main/webapp/WEB-INF/views/board/edit.jsp
src/main/webapp/WEB-INF/views/board/noticedetail.jsp
src/main/webapp/WEB-INF/views/board/noticelist.jsp
src/main/webapp/WEB-INF/views/board/noticewrite.jsp
src/main/webapp/WEB-INF/views/board/replydetail.jsp
src/main/webapp/WEB-INF/views/board/replywrite.jsp
src/main/webapp/WEB-INF/views/board/searchlist.jsp
src/main/webapp/WEB-INF/views/board/write.jsp

admin left 추가 

---

src/main/java/com/wonjoejo/myapp/controller/ProductController.java
src/main/java/com/wonjoejo/myapp/util/QRUtils.java

QRUtils 수정

---

src/main/webapp/WEB-INF/views/admin/list.jsp
src/main/webapp/WEB-INF/views/admin/searchList.jsp
src/main/webapp/WEB-INF/views/admin/searchList0.jsp
src/main/webapp/WEB-INF/views/admin/searchList1.jsp
src/main/webapp/WEB-INF/views/board/detail.jsp
src/main/webapp/WEB-INF/views/board/edit.jsp
src/main/webapp/WEB-INF/views/board/list.jsp
src/main/webapp/WEB-INF/views/board/noticedetail.jsp
src/main/webapp/WEB-INF/views/board/noticelist.jsp
src/main/webapp/WEB-INF/views/board/noticewrite.jsp
src/main/webapp/WEB-INF/views/board/replydetail.jsp
src/main/webapp/WEB-INF/views/board/replywrite.jsp
src/main/webapp/WEB-INF/views/board/searchlist.jsp
src/main/webapp/WEB-INF/views/board/write.jsp
src/main/webapp/WEB-INF/views/box/createview.jsp
src/main/webapp/WEB-INF/views/box/detail.jsp
src/main/webapp/WEB-INF/views/box/editview.jsp
src/main/webapp/WEB-INF/views/box/list.jsp
src/main/webapp/WEB-INF/views/errorPage.jsp
src/main/webapp/WEB-INF/views/group/editview.jsp
src/main/webapp/WEB-INF/views/group/grouplist.jsp
src/main/webapp/WEB-INF/views/group/permissionlist.jsp
src/main/webapp/WEB-INF/views/member/login.jsp
src/main/webapp/WEB-INF/views/member/loginIndex.jsp
src/main/webapp/WEB-INF/views/member/myPage.jsp
src/main/webapp/WEB-INF/views/member/register.jsp
src/main/webapp/WEB-INF/views/product/list.jsp
src/main/webapp/resources/assets/css/group.css
src/main/webapp/resources/assets/js/myPage.js

title 오타 수정  

---

src/main/webapp/resources/assets/js/boxleftmobile.js
src/main/webapp/resources/assets/js/leftmobilemenu.js

모바일 메뉴 콘솔 오류

---

src/main/java/com/wonjoejo/myapp/controller/BoxController.java
src/main/java/com/wonjoejo/myapp/controller/KakaoController.java
src/main/java/com/wonjoejo/myapp/controller/ProductController.java
src/main/java/com/wonjoejo/myapp/util/QRUtils.java
src/main/webapp/resources/assets/js/baseCategory.js
src/main/webapp/resources/assets/js/box.js
src/main/webapp/resources/assets/js/boxmenu.js
src/main/webapp/resources/assets/js/mention.js
src/main/webapp/resources/assets/js/productDetail.js
src/main/webapp/resources/assets/js/register.js

Comment: 주석 추가
